version: '3'
services:
  redis:
    image: redis:latest
    restart: always
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - /tmp
  web:
    restart: always
    build:
      context: ./hubot
      dockerfile: "Dockerfile.web"
    volumes:
      - ./hubot/scripts:/home/hubot/scripts
    ports:
      - '9999:9999'
    env_file: ./hubot/.env
    environment:
      TZ: Asia/Tokyo
    links:
      - redis
