version: '3'
services:
  redis:
    image: redis:latest
    restart: always
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - /tmp
  hubot_slack:
    restart: always
    build: .
    volumes:
      - ./scripts:/home/hubot/scripts
    ports:
      - '9999:9999'
    env_file: .env
    environment:
      TZ: Asia/Tokyo
    links:
      - redis
